# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  merge-me:
    name: Merge me!
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest

    needs: [build]

    strategy:
      matrix:
        node-version: [ 15.x ]

    steps:
      - name: Merge me!
        uses: ridedott/merge-me-action@master
        with:
          GITHUB_LOGIN: dependabot[bot]
          GITHUB_TOKEN: ${{ secrets.MERGE_ME_GITHUB_TOKEN }}
          MERGE_METHOD: SQUASH
          PRESET: DEPENDABOT_MINOR

  build:
    runs-on: ubuntu-latest

    needs: [analyze]

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
        run: npm ci
      - name: Lint code
        run: npm run lint
      - name: Build swagger-adjust
        run: npm run build
      - name: Run security autid on dependencies
        run: npm run security-audit
        env:
          CI: true

      - name: Install demo dependencies
        run: npm ci
        working-directory: ./demo
      - name: Build demo
        run: npm run build
        working-directory: ./demo
      - name: Upload build artifacts
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: ./demo/build

  analyze:
    name: Analyze
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        language: [ 'javascript' ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: ${{ matrix.language }}
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1

  deploy:
    name: Deploy demo
    if: github.ref == 'refs/heads/main'

    needs: [ build ]
    runs-on: ubuntu-latest

    steps:
      - name: Download math result for job 1
        uses: actions/download-artifact@v2
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: build # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
